"""Create paid status column

Revision ID: 3fd2c4d3582e
Revises: 7456186fe18d
Create Date: 2025-04-19 23:51:56.806635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3fd2c4d3582e"
down_revision: Union[str, None] = "7456186fe18d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE paymentstatusenum AS ENUM ('paid', 'pending', 'overdue')")
    op.add_column(
        "invoice",
        sa.Column(
            "paid_status",
            sa.Enum("paid", "pending", "overdue", name="paymentstatusenum"),
            nullable=False,
            server_default="pending",
        ),
    )
    op.drop_column("invoice", "paid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice", sa.Column("paid", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("invoice", "paid_status")
    op.execute("DROP TYPE paymentstatusenum")
    # ### end Alembic commands ###
